### ISSUE TITLE
Feature request: Add OpenDNS support

### ISSUE THREAD

**Issue by lurpware** [qdm12/ddns-updater#121]
1. What's the feature?
   Add support to update an OpenDns IP address registration

2. Why do you need this feature?
   We use OpenDns as our web filter. To filter our DNS lookups it needs to know our current external IP address.

3. Extra information?
They support dyndns2, so it should be relativity easy, I hope... 
https://support.opendns.com/hc/en-us/articles/227987727-Linux-IP-Updater-for-Dynamic-Networks

**Comment by qdm12** [comment]
On it, note that [it supports being updated](https://support.opendns.com/hc/en-us/articles/227987767-Using-Dynamic-DNS-with-OpenDNS) using http://www.dnsomatic.com/ which is supported by the container, if you want to try it out 😉

**Comment by qdm12** [comment]
Can you please let me know the message returned and HTTP status code (either use your browser and check in its console or use [Postman](https://www.postman.com/downloads/)) for the following URLs? Please also replace the values with yours:

- https://yourusername:yourpassword@updates.opendns.com/nic/update?hostname=yoursubdomain.yourdomain.com&myip=youripaddress
- https://yourusername:yourpassword@updates.opendns.com/nic/update?hostname=yoursubdomain.yourdomain.com
- https://yourusername:yourpassword@updates.opendns.com/nic/update?hostname=somegarbagedomain.com&myip=youripaddress
- https://yourusername:yourpassword@updates.opendns.com/nic/update?hostname=yoursubdomain.yourdomain.com&myip=garbageblabla

So that I can write the code to react to all the possible issues. Also if `/nic/update` does not work, try with `/v2/update` instead?

Thanks!

**Comment by lurpware** [comment]
All of the requests returned a 200 with a body of "good xxx.xxx.xxx.xxx"
without the quotes and the x's are my external IP address

The only time I got an error is when I had a bad username/password
That gives me a 401 and a body of "badauth"

When I tried /v2/update I get 404's

Thanks for your willingness and your great project.

--Matt

**Comment by qdm12** [comment]
Thanks! Once [the build finishes](https://github.com/qdm12/ddns-updater/pull/126/checks?check_run_id=1520409268), can you please try with the image with tag `:opendns` and using [this readme](https://github.com/qdm12/ddns-updater/tree/opendns)? Thanks!

**Comment by lurpware** [comment]
Sorry for the late response, Life and stuff... I was able to get it to
work!!!
Some comments, "opendns" needs to be added to the list of providers in the
readme. Also, I don't think OpenDns uses the Domain and Host properties (so
they might need to be removed from the readme).

--Matt

**Comment by qdm12** [comment]
Thanks for trying it! The host is your subdomain or `@` for no subdomain. Your hostname is a fully qualified domain name like sub.domain.com right? If so, sub is the host and domain.com is the domain.

**Comment by qdm12** [comment]
Hey there, so I followed the dyndns specification to build the http query to opendns.

The request is an HTTP GET request in the form `https://user:password@updates.opendns.com/nic/update?hostname=subdomain.domain.com`

So can you have a subdomain and domain for opendns? Or is it just domains? Or only subdomains with a fixed domain?? Thanks!

**Comment by qdm12** [comment]
Hey just a quick reminder if you don't mind answering the questions above. Otherwise I'll merge it in the coming few days. Thanks!

**Comment by AnthonyCW1999** [comment]
This is old, but there are no domains for OpenDNS. You just name your 'network' then when that IP asks for an IP the server can send a customized one. You need to keep your IP updated on the site otherwise it won't send you custom DNS lists.
