### ISSUE TITLE
opendns something wrong

### ISSUE THREAD

**Issue by cnjack** [qdm12/ddns-updater#14]
```
~ curl https://diagnostic.opendns.com/myip
curl: (60) SSL certificate problem: unable to get local issuer certificate
More details here: https://curl.haxx.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
```

change https to http is ok 
```
~ curl http://diagnostic.opendns.com/myip
xxx.xxx.xxx
```

**Comment by qdm12** [comment]
Where do you use `curl` for opendns? Does it give the same error with Go? If so, it can be an issue with expired ca-certificates I think.

**Comment by cnjack** [comment]
yes, got the same err from go
```
docker logs ddns-updater
```
will get the ssl certificate error

**Comment by qdm12** [comment]
Yes indeed, thanks for letting me know. It seems any `wget` gives an SSL error although i. e. Chromium loads the page just fine. I'm still investigating. I will however remove the openDns option because using http or unverified https allows a man in the middle attack and fiddling with domain names and their IPs is quite dangerous.

**Comment by cnjack** [comment]
09-18-2019 ssl will be expired,I think it will be ok
