### ISSUE TITLE
Provider: www.zoneedit.com

### ISSUE THREAD

**Issue by GeorgesOrwell** [qdm12/ddns-updater#226]

**Comment by fredericrous** [comment]
example of dns update with zoneedit: https://gist.github.com/cole/745022

**Comment by qdm12** [comment]
@Waffull @kornface13 @AngusNB @Robbocop1389 @GeorgesOrwell


Please try image tag `:pr-482` and report if it works here, documentation is at https://github.com/qdm12/ddns-updater/blob/zoneedit/docs/zoneedit.md Thanks!

**Comment by Waffull** [comment]
> @Waffull @kornface13 @AngusNB @Robbocop1389 @GeorgesOrwell
> 
> Please try image tag `:pr-482` and report if it works here, documentation is at https://github.com/qdm12/ddns-updater/blob/zoneedit/docs/zoneedit.md Thanks!

It appears to work, thank you. 

I have run into two small issues:

1.  The response from zoneedit isn't recognized: `2023-06-12T22:51:35Z ERROR unknown response received: <SUCCESS CODE="200" TEXT="vt-test.xxxxxx.com updated to xxx.xx.xx.xx" ZONE="xxxxxx.com">`   Thus the status page doesn't show accurate data [https://i.imgur.com/x7lDaLP.png](url)
2. Apparently zoneedit wants at least 10 minutes between updates.  By default the docker image is set to 5m.  I changed the --health-interval to 30m, but an attempt to update was still made.  How would one set the UPDATE_COOLDOWN_PERIOD using the docker run command?

Thanks for the help with zoneedit and getting it working.  Will it be incorporated into the :latest image, at some point?

**Comment by qdm12** [comment]
@Waffull thanks for the feedback:

1. Ah interesting, so it is NOT a clone of easydns, its responses are different. It's not handling properly:
    - success case (also extracting the ip address from the response and checking it against the ip sent out for update)
    - the 600seconds not respected error, treated as abuse (and hence using the cooldown period)
    - failed login error
    - invalid hostname error
    - there may be other errors but it's not documented, so I'll just stuff them in the unknown response received error.
2. You can set it to what you want with `PERIOD=11m`. The cooldown period should not be changed ideally I would say. This raises the point we should be able to specify a period PER record instead of globally. A bit of a niche feature, but that would be useful in this case where zoneedit is 10 min minimum and some others might not enforce this, I created #485 for this.

I went ahead and merged the pull request, so it's now supported in the latest image, as well as in future release v2.6.0
