### ISSUE TITLE
`changeip.com`

### ISSUE THREAD

**Issue by Tulip44** [qdm12/ddns-updater#229]

**Comment by fredericrous** [comment]
https://www.changeip.com/accounts/index.php?rp=/knowledgebase/34/DDNS-API-Information.html

**Comment by qdm12** [comment]
From duplicate issues: @kssxs @johannstieger

**Comment by Savasdotexe** [comment]
Any update to this?

**Comment by qdm12** [comment]
Done in 2f88d44af79d9703102d45dbdcdc8bcd90533b19

**Comment by Savasdotexe** [comment]
I am using truenas and using the latest version, yet for some reason cannot locate changeip on the provider list. Unsure if this has been added or am I doing it wrong? Thought instead of creating a new topic, just continue from this. I hope that's ok.
![image](https://github.com/user-attachments/assets/2f635811-c11d-4394-ba57-b8f255e967e2)
