### ISSUE TITLE
Gotify env variables problem. (Upgrade docker image)

### ISSUE THREAD

**Issue by pablomenino** [qdm12/ddns-updater#26]
Hi, in the last version I have this error. 

`
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x8e781b]
goroutine 1 [running]:
main.setupGotify(0xbc4060, 0xc00049ed20, 0x0, 0x1, 0x1, 0xb2d05e00)
	/tmp/gobuild/main.go:120 +0xeb
main.main()
	/tmp/gobuild/main.go:53 +0x604
`

It seems an error whit Gotify, Adding env variables for gotify solve the issue.
I have a Gotify server so is no problem, but this may be a problem for other people.

----
Rollback to version Nov 28, 2019, everything is fine here.

**Comment by jenga201** [comment]
I'm having this issue also.

What environment variables did you add?

This container isn't tagged, so it's only possible to pull the latest version.

**Comment by qdm12** [comment]
Thanks for letting me know! Yes I have changed some things yesterday, I'll fix this now.

**Comment by qdm12** [comment]
It should be fixed with the latest commit. It might take 30-45 minutes to build the Docker image for Docker Hub (I don't have my Docker credentials on me).

Alternatively you can build the image with:

```sh
docker build -t qmcgaw/ddns-updater https://github.com/qdm12/ddns-updater.git
```

You can also revert back to another commit by following/adapting the instructions of this [section](https://github.com/qdm12/private-internet-access-docker/blob/master/README.md#troubleshooting), and build the Docker image locally. I'll add some long due Docker tagging tonight.

**Comment by qdm12** [comment]
I just pulled the image now and tested without Gotify and it works now. Sorry for the trouble!

**Comment by jenga201** [comment]
Works for me, too.  Thanks!

**Comment by qdm12** [comment]
There is a tag I just made, `v1` so in case I break something you can fallback to it with

```sh
docker pull qmcgaw/ddns-updater:v1
```
