### ISSUE TITLE
Error on ip method

### ISSUE THREAD

**Issue by Marketos-Damigos** [qdm12/ddns-updater#27]
As it seems duckduckgo doesnt return the ip anymore, also google and opendns return this error:
In godaddy you cant use provider so no option to get the ip. Although both google and opendns return results.
Google
{"level":"WARN","ts":"2020-01-06T16:45:39.954Z","msg":"IP method google not recognized","node_id":0}
{"level":"FATAL","ts":"2020-01-06T16:45:39.954Z","msg":"no settings found in config.json","node_id":0}

OpenDNS
{"level":"WARN","ts":"2020-01-06T16:46:53.008Z","msg":"IP method opendns no longer supported","node_id":0}
{"level":"FATAL","ts":"2020-01-06T16:46:53.008Z","msg":"no settings found in config.json","node_id":0}

**Comment by qdm12** [comment]
Sorry I closed it by mistake. I think you are running an outdated Docker image, that's why.

Please wait like 45 minutes (latest image is being built with a fix for #26) for the Docker image is to be built and then

```sh
docker pull qmcgaw/ddns-updater
```

and restart your container and it should work. Feel free to reopen the issue if anything doesn't work.
