### ISSUE TITLE
`namesilo.com`

### ISSUE THREAD

**Issue by seaneoz** [qdm12/ddns-updater#313]
Can you add namesilo ddns updater？

**Comment by calonmerc** [comment]
I second this request.

[NameSilo add DNS record](https://www.namesilo.com/api-reference#dns/dns-add-record)

[NameSilo update DNS record](https://www.namesilo.com/api-reference#dns/dns-update-record)

**Comment by kssxs** [comment]
Any chance this might get done in the near future?

I'd really rather use this updater than some of the others out there, due to it's robustness and popularity.

Thanks in advance, and if asking violated some rule that I missed, my apologies!

**Comment by Zeustopher** [comment]
I started on this, but I've decided to move to my management of DNS for my domains to Cloudflare, so I've lost motivation to continue working on it. I didn't make it far - just primarily research the api, make the start of a readme, and take a screenshot of where to click to manage DNS. Instead of doing a full PR I'll just include the little bit of work here:

<details>
  <summary>README</summary>
  
# Namesilo

[![Namesilo Logo](https://www.namesilo.com/static/assets/img/logo.png)](https://www.namesilo.com/)

## Configuration

### Example

```json
{
  "settings": [
    {
      "provider": "namesilo",
      "domain": "domain.com",
      "host": "home",
      "key": "71dZaE8c2Aa926Ca2E8c1",
      "ip_version": "ipv4"
    }
  ]
}
```

### Compulsory parameters

- `"domain"` your domain. Example: `domain.com`.
- `"host"` your host. Can be a subdomain or `"@"` or `"*"`. Example: `home` to update the record for `home.domain.com`.
- `"key"` the api key obtained using domain setup instructoins below. Example: `71dZaE8c2Aa926Ca2E8c1`.

### Optional parameters

- `"ip_version"` can be `ipv4` (A records), or `ipv6` (AAAA records) or `ipv4 or ipv6` (update one of the two, depending on the public ip found). It defaults to `ipv4 or ipv6`.

## Domain setup

1. Login to [Namesilo API Manager](https://www.namesilo.com/account/api-manager) with your account credentials.

1. Generate an API key. The generated API key will look similar to `71dZaE8c2Aa926Ca2E8c1`.
    - (do _not_ check the "Generate key for read-only access" box)

## Testing

1. Go to [domain manager](https://www.namesilo.com/account_domains.php).
1. Choose "Manage DNS for this domain" (the globe icon) for the domain you wish to test.
    ![manage domain](../readme/namesilo_domain_dns_manage.png)
    ![namesilo_domain_dns_manage](https://github.com/qdm12/ddns-updater/assets/11470532/9ce63f54-1440-4180-98df-b4d73a17b416)
1. Change the IP address of the host to `127.0.0.1`.
1. Run the ddns-updater.
1. Refresh the Namesilo webpage to check the update occurred.

## Other references

- [Namesilo API Reference](https://www.namesilo.com/api-reference)
 
</details>
