### ISSUE TITLE
Feature request: LISTENING_ADDRESS variable

### ISSUE THREAD

**Issue by edaubert** [qdm12/ddns-updater#576]
1. What's the feature?
Currently we can specify the TCP port used to provide the Web UI (`LSITENING_PORT`) and all the IP addresses of the host are used as available addresses to connect on this port.

I would like to be able to specify the address on which the UI is available.
For example, I only want the Web UI on a specific sub network.

2. Extra information?
I saw on [the code ](https://github.com/qdm12/ddns-updater/blob/master/internal/config/sources/env/server.go#L7) that you were planning at some point to replace `LISTENING_PORT` by something like `LISTENIING_ADDRESS` or to add this variable and keep the other.

I can do a proposal about it but before that, I would like to know your thoughts about it.
- Would you like to be able to define multiple addresses with the variable ?
- Would you prefer to keep `LISTENING_PORT` for backward compatibility ?

**Comment by qdm12** [comment]
Thanks for the suggestion!
I did it myself since I wanted to upgrade a settings reading library dependency before doing it (ab6908b8cc360f68f91c0ca43e8ed3b52b2f3640), now it's sitting in PR https://github.com/qdm12/ddns-updater/pull/590/files

> Would you like to be able to define multiple addresses with the variable ?

It's possible, it would take me a few minutes, but the code would get rather ugly (need to run N parallel http servers in goroutines) so I would rather avoid. Would you have a use case for this? 🤔

**Comment by edaubert** [comment]
Hi,

Your PR seems good to me and better than what I have started :smile: 
No specific use case for multiple addresses, it was a simple question to know what I should have as requirement if I provide a PR.

Hope to see your PR soon on a release :+1:

**Comment by qdm12** [comment]
Merged! So, no use case for multiple addresses then right?
