### ISSUE TITLE
Invalid Syntax with Newest Update

### ISSUE THREAD

**Issue by ThomasHineXYZ** [qdm12/ddns-updater#591]
Looks like this newest update broke the Dockerfile.

https://github.com/qdm12/ddns-updater/blob/3e638326edc3d74012d347a45728380c49598baf/Dockerfile#L89

![image](https://github.com/qdm12/ddns-updater/assets/6890628/2b982ffd-f91c-4512-ad80-560a10efb48a)

**Comment by Schwenksen** [comment]
Yes, same here. Is there some known quick fix solution?

**Comment by qdm12** [comment]
Working on a fix!

**Comment by qdm12** [comment]
8dc39453e1be713a12a51965dcc811370ae54b45 should fix it. It was because I changed from `LISTENING_PORT=8000` to `LISTENING_PORT=:8000` in the Docker image, instead it should had been `LISTENING_ADDRESS=:8000`. The old variable `LISTENING_PORT` should still work as before though. Thanks for taking the time to report the bug, and sorry about it!
