### ISSUE TITLE
"no valid settings was found in the environment variables" w/Docker Compose?

### ISSUE THREAD

**Issue by DivinityCycle** [qdm12/ddns-updater#7]
Docker Compose file contents:
>version: "3.7"
services:
  ddns:
    container_name: ddns
    image: qmcgaw/ddns-updater
    restart: unless-stopped
    ports:
      - 8000:8000
    volumes:
      - ./ddns:/updater/data
    environment:
      - DELAY=60
      - LISTENINGPORT=8000
      - LOGGING=human
      - NODEID=0

When deploying this, I receive the following two error messages regardless of what variations I try:

> ddns    | {"level":"Warning","message":"The RECORDn environment variables will be removed and replaced by the config.json file in the coming months. Please update your container configuration as soon as possible to avoid problems once the retrocompatibility is removed. See more information on github.com/qdm12/ddns-updater","time":"2019-05-16T00:25:15.882564592Z","node":0}
ddns    | {"level":"Warning","message":"no valid settings was found in the environment variables","time":"2019-05-16T00:25:15.882772979Z","node":0}

Is this just a logging logic issue, or is DDNS Updater really unable to read these variables? If so, why not?

**Comment by qdm12** [comment]
Hi there,

That's the expected behavior.

The first warning is to highlight to users the move from legacy `RECORDi` type of environment variables record settings to config.json as I will remove support for it in the coming few days.

The second warning means the program did not find any legacy `RECORDi` settings, but is fine as long as you have records in config.json. I will remove this warning as well once I remove support as mentioned above. I will probably remove it next Monday to avoid confusion to new users.
