### ISSUE TITLE
Bug: Ionos wildcard handling

### ISSUE THREAD

**Issue by Cilenco** [qdm12/ddns-updater#718]
**TLDR**: Ionos provider creates any AAAA record instead of updating * record

1. Is this urgent: Yes
2. DNS provider(s) you use: Ionos
3. Program version:  `Running version 2.6.0 built on 2024-02-03T18:53:40.722Z (commit c338c28)`
4. What are you using to run the container: docker-compose
5. Extra information

![ionos bug](https://github.com/qdm12/ddns-updater/assets/4381287/dacf2db8-2bbe-41ed-ae24-62ebe51d104a)

Logs:

```
INFO Updating record [domain: domain.tld | host: @ | provider: ionos | ip: ipv6] to use <ip6-address>
INFO Updating record [domain: domain.tld | host: * | provider: ionos | ip: ipv6] to use <ip6-address>

```

Configuration file (**remove your credentials!**):

```
{
  "settings": [
    {
      "provider": "ionos",
      "domain": "domain.tld",
      "api_key": "...",
      "ip_version": "ipv6",
      "host": "@,*"
    }
  ]
}

```

Host OS: Raspberry Pi OS (Debian GNU/Linux 12 (bookworm))

**Comment by qdm12** [comment]
aa4a1f381300fcba33d23b2e2e0bde3fcfb0c349 likely fixes this, can you pull the latest image `docker pull qmcgaw/ddns-updater` and try with this image? It was previously setting the name to find/create/update to `any.domain.de` instead of the now-fixed `*.domain.de`, my bad!

If it still doesn't work, can you share what logs you get with the `LOG_LEVEL=debug` set? (remove your credentials!)

**Comment by Cilenco** [comment]
Yes it does work now with the latest image. Thank you for the fix!
