### ISSUE TITLE
name.com IP update sent creates a duplicate entry and does not update the current entry : name.com creating record: bad request sent: Parameter Value Error - Duplicate Record

### ISSUE THREAD

**Issue by CaptainBuzzable** [qdm12/ddns-updater#724]
**TLDR**: *Failure (creating record: bad request sent: Parameter Value Error - Duplicate Record) name.com*

1. Is this urgent: Yes
2. DNS provider(s) you use: name.com
3. Program version: 

    

    `qmcgaw/ddns-updater:2.6.0`

4. What are you using to run the container: docker-compose
5. Extra information (optional)
6. qmcgaw/ddns-updater:2.6.0

Logs:

```log
Failure (creating record: bad request sent: Parameter Value Error - Duplicate Record) name.com
xxxxxx.xxxx  | 2024-05-16T15:05:56Z ERROR creating record: bad request sent: Parameter Value Error - Duplicate Record
```

Configuration file (**remove your credentials!**):

```json
   {
      "provider": "name.com",
      "domain": "xxxxxx.com",
      "host": "@",
      "username": "xxxxxx",
      "token": "xxxxxxxxxxxxxxxx",
      "ttl": 300,
      "ip_version": "ipv4",
      "ipv6_suffix": ""
   }
```

Host OS: Ubuntu Docker

**Comment by qdm12** [comment]
That's kind of strange. The logic is to:

1. Get all records for the domain and search for the record matching the record type (`A`) and the host (i.e. `@`)
2. If not found, send a request to create it
3. If found, update it

I would guess the problem lies in step 1.

Can you please check what you get from accessing `https://username:token@api.name.com/v4/domains/yourdomain.com/records` from your browser (and **replace** `username`, `token` and `yourdomain.com`?

I expect it to be similar to:

```json
{
    "records": [
        {
            "id": 12345,
            "domainName": "yourdomain.com",
            "host": "@",
            "fqdn": "yourdomain.com",
            "type": "A",
            "answer": "1.2.3.4",
            "ttl": 300
        }
    ]
}		
```

Let me know if this matches or if there is a mismatch?

You can also further debug it for me by using `LOG_LEVEL=debug` which logs out every http request and responses.

**Comment by CaptainBuzzable** [comment]
Thanks so much for a quick response; i have added all the output in a word doc for simplicity let me know if you need it plain txt.. really like your software and its saves me creating something similar in golang myself. :)
[duplicate record.docx](https://github.com/qdm12/ddns-updater/files/15428703/duplicate.record.docx)
attached a word doc with the username and api key removed and also some screen shots.. Thanks Mark

**Comment by CaptainBuzzable** [comment]
2024-05-24T06:43:13Z DEBUG config read: {
nameddns.firtreecottage  |   "settings": [
nameddns.firtreecottage  |     {
nameddns.firtreecottage  |       "provider": "name.com",
nameddns.firtreecottage  |       "domain": "firtreecottage.com",
nameddns.firtreecottage  |       "host": "@",
nameddns.firtreecottage  |       "username": ",
nameddns.firtreecottage  |       "token": "xxx",
nameddns.firtreecottage  |       "ttl": 300,
nameddns.firtreecottage  |       "ip_version": "ipv4",
nameddns.firtreecottage  |       "ipv6_suffix": ""
nameddns.firtreecottage  |     }
nameddns.firtreecottage  |   ]
nameddns.firtreecottage  | }

**Comment by CaptainBuzzable** [comment]
When i delete the old duplicate entry its works no update needed.2024-05-24T06:43:13Z INFO Found single setting to update record
2024-05-24T06:43:13Z INFO Reading history from database: domain firtreecottage.com host @ ipv4
2024-05-24T06:43:13Z DEBUG configured to fetch IP: v4 or v6: false, v4: true, v6: false
2024-05-24T06:43:13Z INFO [backup] disabled
2024-05-24T06:43:13Z INFO [http server] listening on :80
2024-05-24T06:43:13Z INFO [healthcheck server] listening on 127.0.0.1:9999
2024-05-24T06:43:13Z DEBUG your public IP address are: v4 or v6: invalid IP, v4: 185.254.149.145, v6: invalid IP
2024-05-24T06:43:13Z DEBUG ipv4 address of firtreecottage.com is 185.254.149.145 and your ipv4 address is 185.254.149.145, skipping update

**Comment by CaptainBuzzable** [comment]
Just check if i delete the a record before the update in name.com it works perfectly.

**Comment by CaptainBuzzable** [comment]
curl -u 'xxxxx:xxxxxx' 'https://api.name.com/v4/domains/firtreecottage.com/records/2460007xx' -X PUT -H 'Content-Type: application/json' --data '{"domainName":"firtreecottage.com","fqdn":"firtreecottage.com ","type":"A","answer":"'$ip'","ttl":300}'

**Comment by CaptainBuzzable** [comment]
The API has changed..

curl -u 'username:token' 'https://api.dev.name.com/v4/domains/example.org/records/12345' -X PUT -H 'Content-Type: application/json' --data '{"host":"www","type":"A","answer":"10.0.0.1","ttl":300}'
{
    "id": 12345,
    "domainName": "example.org",
    "host": "www",
    "fqdn": "www.example.org",
    "type": "A",
    "answer": "10.0.0.1",
    "ttl": 300
}					

Now expects this 

--data '{"domainName":"firtreecottage.com","fqdn":"firtreecottage.com ","type":"A","answer":"10.10.10.1","ttl":300}'.

**Comment by qdm12** [comment]
I believe I found the problem, which is fixed with c1bf7a49c198ce64d74bf6b7bc1e5f92ebe130cb - can you try pulling the latest image and see if it works now?

For details, name.com responds with the "host" field absent for the root host (`@`), so comparing `""` with `"@"` would fail and so the record would not be found. This is now fixed by overriding `""` with `"@"` when going through listed records, before doing the comparison.

**Comment by CaptainBuzzable** [comment]
OK just pulled image: qmcgaw/ddns-updater:latest 16th June,

Now i get this..

nameddns.notinproduction  | 2024-06-16T06:54:18Z INFO ipv4 address of marklucas.co.uk is 10.10.10.10 and your ipv4 address  is 95.166.29.89
nameddns.notinproduction  | 2024-06-16T06:54:18Z INFO Updating record [domain: marklucas.co.uk | host: @ | provider: name.com | ip: ipv4] to use 95.166.29.89
nameddns.notinproduction  | 2024-06-16T06:54:19Z ERROR updating record: bad request sent: Parameter Value Error - Invalid Host: @.marklucas.co.uk


**now delete a record from name.com**. 

completely (no A record at all) in DNS

restart 

| 2024-06-16T06:58:08Z INFO [http server] http server listening on [::]:80
nameddns.notinproduction  | 2024-06-16T06:58:08Z INFO [backup] disabled
nameddns.notinproduction  | 2024-06-16T06:58:09Z INFO ipv4 address of marklucas.co.uk is 10.10.10.10 and your ipv4 address  is 95.166.xx.89
nameddns.notinproduction  | 2024-06-16T06:58:09Z INFO Updating record [domain: marklucas.co.uk | host: @ | provider: name.com | ip: ipv4] to use 95.166.xx.89
mark@docker2:/usb/nameDDNS$

Notes

"domain": "marklucas.co.uk",
      "host": "@",

**Comment by qdm12** [comment]
Are you sure your `"host"` field is `"@"` and not `"@.marklucas.co.uk"`? 🤔 
On the name.com's API UpdateRecord documentation ([here](https://www.name.com/api-docs/dns#UpdateRecord)), it states:

> An apex record would be specified by either an empty host "" or "@"

And for now this is what's done

https://github.com/qdm12/ddns-updater/blob/d3b689d0ef700631a580e1a1c5a9c80a7bd6288c/internal/provider/providers/namecom/updaterecord.go#L30-L40

The same is also done to create a record, and it seems to work which is quite strange:

https://github.com/qdm12/ddns-updater/blob/d3b689d0ef700631a580e1a1c5a9c80a7bd6288c/internal/provider/providers/namecom/createrecord.go#L30-L40

Anyway, I pushed 012a6dddcd388c6110e5ef0006e96c2b1ac18577 to force the host field to be `""` instead of `"@"` when updating a record, since this may be the problem 🤔 Let me know if this resolves it 😉 Also curious about wildcards if you can check it works fine that would be great too!

**Comment by CaptainBuzzable** [comment]
Hello Quentin,
This now works 100% thank you so much for all your amazing help!! -
9:31Z INFO [healthcheck server] health http server listening on
127.0.0.1:9999
nameddns.notinproduction  | 2024-06-16T08:59:31Z INFO [http server] http
server listening on [::]:80
nameddns.notinproduction  | 2024-06-16T08:59:31Z INFO [backup] disabled
nameddns.notinproduction  | 2024-06-16T08:59:31Z INFO ipv4 address of
marklucas.co.uk is 195.166.29.89 and your ipv4 address  is 95.166.29.89
nameddns.notinproduction  | 2024-06-16T08:59:31Z INFO Updating record
[domain: marklucas.co.uk | host: @ | provider: name.com | ip: ipv4] to use
95.166.29.89

No Errors!!! name.com + ddns-updater 10/10 :)

marklucas.co.uk @ Name.com <https://name.com/> ipv4 Success (changed to
95.166.29.89), 3m43s ago 95.166.29.89 <https://ipinfo.io/95.166.29.89>
195.166.29.89

**Comment by CaptainBuzzable** [comment]
A little payment coming your way for a coffee!!

**Comment by CaptainBuzzable** [comment]
Done!!

**Comment by qdm12** [comment]
Awesome, thanks for the little 💸 👍 enjoy!
