### ISSUE TITLE
Feature request: Implement System Variables TZ, UID, GID, and UMASK

### ISSUE THREAD

**Issue by JesterEE** [qdm12/ddns-updater#90]
1. What's the feature?
Pass and respect the system variables: TZ, UID, GID, and UMASK

2. Why do you need this feature?
Keep the host file permission nice and clean when operating docker as an alternate user.

3. Extra information?
Similar to what is done by Linuxserver.io in their docker images (and what is done in the Gluetun docker).

**Comment by qdm12** [comment]
Hello!

For UID, GID and UMASK, I don't think that's possible because some files built-in the image are already owned by `1000:1000`, and it's not possible to change their ownership at runtime. The only way would be to rebuild the image but that's more trouble.

For `TZ` i didn't document it but it should already work, for example `TZ=America/Montreal`. Let's keep it opened so I document it.
